# Generated by Django 6.0.5 on 2026-05-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldocument',
            old_name='is_encyrpted',
            new_name='is_encrypted',
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='documents/encrypted/'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
