# Generated by Django 6.0.5 on 2026-05-11 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ct_scan', 'CT Scan'), ('pet_scan', 'PET Scan'), ('mri', 'MRI'), ('xray', 'X-Ray'), ('blood', 'Qan analizi'), ('urine', 'Sidik analizi'), ('echo', 'EXO (ürək)'), ('other', 'Digər')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('in_progress', 'İcra olunur'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_given', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
